### ISSUE TITLE
Custom classes and html

### ISSUE THREAD

**Issue by Develop-FM** [JavaTMP/bootstrap-modal-wrapper#17]
It would be handy if "dialogCustomClass" (not just sizes) and "titleHtml" (not want h5, etc) options become available.

**Comment by JavaTMP** [comment]
good idea, i will add them to features list.

**Comment by JavaTMP** [comment]
You can now use the `modalTitleContainer` with you custom html as a title container like `modalTitleContainer: "<h1 class='modal-title'></h1>"` at creation time.
and for custom classes you can add them after creation by calling original modal and add them like:
`modalWrapper.originalModal` variable will point to `<div class='modal'>..</div>` element.
`modalWrapper.originalModal.addClass(...);`
